### ISSUE TITLE
Exposing API token in the header?

### ISSUE THREAD

**Issue by web-programmer-here** [baileyherbert/envato.js#9]
When checking the network tab and viewing details I can see this info:

```
GET /v3/market/buyer/purchase?code=PURCHASE-CODE HTTP/2
Host: api.envato.com
User-Agent: Envato.js (https://github.com/baileyherbert/envato.js)
Referer: http://localhost/
authorization: Bearer MY-TOKEN-HERE
x-client: envato.js
Origin: http://localhost
```

as you can see the authorization part includes my API token `MY-TOKEN-HERE` , is this safe to expose it like this?

**Comment by baileyherbert** [comment]
For a private web app, it's safe - that header is required to authenticate the request.

But if that web app will be public to anyone outside of your team (i.e where they can inspect the network headers themselves), then no, you shouldn't be sending requests like that. In such a case you'll actually need to set up your own server-side API which will then connect to the Envato API and keep the token private.

**Comment by web-programmer-here** [comment]
@baileyherbert thanks, yeah I want the users to be able to verify their purchase, do you have a js example for verification that doesnt expose the api key?

**Comment by baileyherbert** [comment]
Just so it's said: this package is only intended for server-side usage, meaning users shouldn't be able to access that information. 

Verifying a purchase code without sending that header is impossible with any code snippet.

You'd have to send the user's request to your own API, such as

https://api.yourdomain.com/verify?code=

This URL would be using Envato.js behind the scenes, probably leveraging `express` as the webserver, with its token nice and safe in order to check the purchase code and return the response. The code examples in the readme will work fine for this side of things.

Then you'll just need to make the connection from your user's side to https://api.yourdomain.com/verify using fetch or something.

**Comment by web-programmer-here** [comment]
oh this makes sense, thank you

**Comment by baileyherbert** [comment]
And just as an FYI, if you'd be more comfortable working with PHP on the server side, I have a function here that you could use:

https://forums.envato.com/t/how-to-verify-a-purchase-code-using-the-envato-api/150813#php-function-14
